type: "csv"
csv_path: "lukasz-staniszewski/patching-music-musiccaps-prompts"
feature: null
prefix_clean: ""
suffix_clean: ""
prefix_corrupted: ""
suffix_corrupted: ""

eval_clap_prompts:
  - good-sounding music
  - high quality song
  - high quality music

eval_muqt_prompts:
  - good-sounding music
  - high quality song
  - high quality music
