type: "csv"
csv_path: "lukasz-staniszewski/patching-music-musiccaps-prompts"
feature: "saxophone"
prefix_clean: ""
suffix_clean: ""
prefix_corrupted: ""
suffix_corrupted: ""

eval_clap_prompts:
  - saxophone music

eval_muqt_prompts:
  - saxophone music
