type: "csv"
csv_path: "lukasz-staniszewski/patching-music-musiccaps-prompts"
feature: "slow"
prefix_clean: ""
suffix_clean: ""
prefix_corrupted: ""
suffix_corrupted: ""

eval_clap_prompts:
  - fast song
  - slow song

eval_muqt_prompts:
  - fast
  - slow