method: audioldm_caa
method-kwargs: {target_layers: up1_late7}
artifact: lukasz-staniszewski/audioldm2-caa-tempo
concept: tempo
alphas: [0.0, 0.6667, 1.3333, 2.0, 2.6667, 3.3333, 4.0, 4.6667, 5.3333, 6.0, 6.6667, 7.3333, 8.0, 8.6667, 9.3333, 10.0]
duration: 10.0
steps: 100
guidance-scale: 4.5
seed: 2115
batch-size: 8
save-dir: outputs/eval/audioldm_caa_loc_tempo
