n_latents_per_prompt: 8
seed: 222
batch_size: 32
num_inference_steps: 50
guidance_scale: 7.0
audio_dirname: "audios"
path_with_results: null
save_per_gpu: true
method: "patch"
audio_duration: 30.0
lyrics: ""
guidance_scale_lyric: 1.0
guidance_scale_text: 6.0
guidance_interval: 1.0
scheduler_type: "euler"
cfg_type: "apg"
omega_scale: 7.0
save_clean_audio: false
pad_to_max_len: 128