layers_to_patch:
  - '.ace_step_transformer.transformer_blocks.0.cross_attn'
  - '.ace_step_transformer.transformer_blocks.1.cross_attn'
  - '.ace_step_transformer.transformer_blocks.2.cross_attn'
  - '.ace_step_transformer.transformer_blocks.3.cross_attn'
  - '.ace_step_transformer.transformer_blocks.4.cross_attn'
  - '.ace_step_transformer.transformer_blocks.5.cross_attn'
  - '.ace_step_transformer.transformer_blocks.6.cross_attn'
  - '.ace_step_transformer.transformer_blocks.7.cross_attn'
  - '.ace_step_transformer.transformer_blocks.8.cross_attn'
  - '.ace_step_transformer.transformer_blocks.9.cross_attn'
  - '.ace_step_transformer.transformer_blocks.10.cross_attn'
  - '.ace_step_transformer.transformer_blocks.11.cross_attn'
  - '.ace_step_transformer.transformer_blocks.12.cross_attn'
  - '.ace_step_transformer.transformer_blocks.13.cross_attn'
  - '.ace_step_transformer.transformer_blocks.14.cross_attn'
  - '.ace_step_transformer.transformer_blocks.15.cross_attn'
  - '.ace_step_transformer.transformer_blocks.16.cross_attn'
  - '.ace_step_transformer.transformer_blocks.17.cross_attn'
  - '.ace_step_transformer.transformer_blocks.18.cross_attn'
  - '.ace_step_transformer.transformer_blocks.19.cross_attn'
  - '.ace_step_transformer.transformer_blocks.20.cross_attn'
  - '.ace_step_transformer.transformer_blocks.21.cross_attn'
  - '.ace_step_transformer.transformer_blocks.22.cross_attn'
  - '.ace_step_transformer.transformer_blocks.23.cross_attn'
