method: pci
artifact: ""
concept: vocal_style
alphas: [-30, -28, -26, -24, -22, -20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
method-kwargs: {target_layers: all}
duration: 30.0
steps: 30
guidance-scale: 5.0
seed: 2115
save-dir: outputs/eval/pci_all_vocal_style
