scorer: concept_slider
concept: electronic_music
output: steering_vectors/concept_slider/ace_electronic_music_r8_eta7_500_all
no-model: true
scorer-kwargs:
  iterations: 500
  eta: 7
  layers: all
  num_prompts: 100
