MUSICCAPS_ORIGINAL_FEATURES = {
    "female": ["female", "woman", "girlish"],
    "male": ["male", "man"],
    "fast": [
        "fast",
        "rapid",
        "dynamic",
        "quick",
        "quickly",
        "fastly",
        "energetic",
        "tireless",
        "sprightly",
        "energetic",
        "groovy",
        "lively",
        "fast-paced",
        "vigorous",
    ],
    "slow": [
        "slow",
        "slowed",
        "slower",
        "slowly",
        "slow-paced",
        "leisurely",
        "sedate",
        "plodding",
        "slow-moving",
    ],
    "happy": ["happy", "joyful", "upbeat", "uplifting", "cheerful"],
    "sad": ["sad", "depressing", "dejected", "depressing", "dejected"],
    "reggae": ["reggae", "jamaican", "tropical", "summer", "vacation", "beach"],
    "metal": ["metal", "heavy", "rock"],
    "jazz": ["jazz", "blues"],
    "opera": ["opera", "choir", "orchestra"],
    "violin": ["violin", "fiddle"],
    "trumpet": ["trumpet", "trumpets"],
    "saxophone": ["saxophone", "sax", "saxophones"],
    "drums": ["drums", "drum", "percussion"],
    "cello": ["cello", "cellos"],
    "bongos": ["bongos", "bongo"],
    "flute": ["flute", "flutes"],
    "maracas": ["maracas", "maraca"],
    "harmonica": ["harmonica", "harmonicas"],
    "trombone": ["trombone", "trombones"],
    "xylophone": ["xylophone", "xylophones"],
}
MUSICCAPS_COUNTERFACTUAL_FEATURES = {
    "female": ["male", "man"],
    "male": ["female", "woman", "girl", "lady", "her", "she"],
    "fast": ["slow", "slowed", "slower", "slowly"],
    "slow": [
        "fast",
        "rapidly",
        "quickly",
        "fastly",
        "energetic",
        "tireless",
        "sprightly",
        "groovy",
        "lively",
        "fast-paced",
        "vigorous",
    ],
    "happy": ["sad", "depressing", "dejected", "depressing", "dejected"],
    "sad": [
        "passionate",
        "joyful",
        "fun",
        "cheerful",
        "warm",
        "high-spirited",
        "lively",
        "enthusiastic",
        "energetic",
        "engaging",
        "vivacious",
        "happy",
        "enthusiastically",
        "danceable",
        "light",
        "positive",
        "upbeat",
        "uplifting",
        "pulsating",
        "loud",
        "punchy",
        "buoyant",
        "youthful",
        "vibrant",
    ],
    "reggae": ["metal", "heavy", "rock", "opera", "choir", "orchestra", "classical"],
    "metal": ["reggae", "rock", "opera", "choir", "orchestra", "classical"],
    "jazz": ["reggae", "rock", "opera", "choir", "orchestra", "classical"],
    "opera": ["reggae", "rock", "metal", "heavy", "jazz"],
    "violin": ["trumpet"],
    "trumpet": ["violin", "violins", "fiddle", "fiddles"],
    "saxophone": ["drum", "drums", "percussion"],
    "drums": ["saxophone", "sax", "saxophones"],
    "cello": ["bongo", "bongos"],
    "bongos": ["cello", "cellos"],
    "flute": ["maracas", "maraca"],
    "maracas": ["flute", "flutes"],
    "harmonica": ["harp", "harps", "harpist", "harpists"],
    "trombone": ["xylophone", "xylophones", "xylophonist", "xylophonists"],
    "xylophone": ["trombone", "trombones"],
}

MUSICCAPS_SWAPS_FEATURES = {
    "female": {
        "female": "male",
        "woman": "man",
        "her": "his",
        "girlish": "boyish",
        "she": "he",
    },
    "male": {
        "male": "female",
        "man": "woman",
        "boy": "girl",
        "his": "her",
        "him": "her",
        "himself": "herself",
        "he": "she",
    },
    "fast": {
        "fast": "slow",
        "rapid": "slow",
        "dynamic": "slow",
        "quick": "slow",
        "quickly": "slowly",
        "fastly": "slowly",
        "energetic": "slow",
        "tireless": "slow",
        "sprightly": "slowly",
        "groovy": "slowly",
        "lively": "slowly",
        "fast-paced": "slow-paced",
        "vigorous": "slow",
    },
    "slow": {
        "slow": "fast",
        "slowed": "fasted",
        "slower": "faster",
        "slowly": "fastly",
        "slow-paced": "fast-paced",
        "leisurely": "hastily",
        "sedate": "agitated",
        "romantic": "action",
        "plodding": "quick",
        "slow-moving": "fast-moving",
    },
    "happy": {
        "passionate": "apathetic",
        "joyful": "sorrowful",
        "fun": "dreary",
        "cheerful": "gloomy",
        "warm": "cold",
        "high-spirited": "downcast",
        "lively": "lifeless",
        "enthusiastic": "disheartened",
        "energetic": "weary",
        "engaging": "detached",
        "vivacious": "melancholic",
        "happy": "sad",
        "enthusiastically": "reluctantly",
        "danceable": "plodding",
        "light": "heavy",
        "positive": "negative",
        "vibrant": "dull",
        "upbeat": "downbeat",
        "pulsating": "flat",
        "loud": "quiet",
        "punchy": "muted",
        "buoyant": "heavy-hearted",
        "youthful": "world-weary",
        "uplifting": "depressing",
    },
    "sad": {
        "sad": "happy",
        "depressing": "joyful",
        "dejected": "cheerful",
        "depressing": "cheerful",
        "dejected": "joyful",
        "haunting": "uplifting",
        "melancholic": "cheerful",
        "emotional": "lighthearted",
        "pensive": "carefree",
        "regretful": "content",
        "contemplative": "playful",
        "wistful": "hopeful",
        "meditative": "breezy",
        "crying": "laughing",
        "soulful": "spirited",
        "lonely": "connected",
        "poignant": "joyous",
        "mellow": "vibrant",
    },
    "reggae": {
        "reggae": "metal",
        "jamaican": "metal",
        "tropical": "metal",
        "chill": "heavy",
        "summer": "concert",
        "vacation": "concert",
        "paradise": "concert",
        "beach": "concert",
    },
    "metal": {
        "metal": "reggae",
        "heavy": "chill",
    },
    "jazz": {
        "jazz": "opera",
        "blues": "opera",
        "band": "choir",
    },
    "opera": {
        "opera": "jazz",
        "choir": "blues",
        "orchestra": "band",
        "classical": "jazz",
    },
    "violin": {
        "violin": "trumpet",
        "fiddle": "trumpet",
        "string": "",
        "strings": "",
        "violins": "trumpet",
        "violinist": "trumpeter",
    },
    "trumpet": {"trumpet": "violin", "trumpeter": "violinist", "trumpets": "violins"},
    "saxophone": {
        "saxophone": "drum",
        "sax": "drum",
        "saxophones": "drums",
        "saxophonist": "drummer",
        "saxophonists": "drummers",
    },
    "drums": {
        "drums": "saxophone",
        "drum": "saxophone",
        "percussion": "saxophone",
        "percussionist": "saxophonist",
        "percussionists": "saxophonists",
        "drummer": "saxophonist",
    },
    "cello": {
        "cello": "bongo",
        "cellos": "bongos",
        "cellist": "bongomaster",
        "cellists": "bongomasters",
        "celloist": "bongomaster",
        "celloists": "bongomasters",
    },
    "bongos": {
        "bongos": "cello",
        "bongo": "cello",
        "bongomaster": "cellist",
        "bongomasters": "cellists",
    },
    "flute": {
        "flute": "maracas",
        "flutes": "maracas",
        "flutist": "maracast",
        "flutists": "maracasts",
        "fluteist": "maracast",
        "fluteists": "maracasts",
    },
    "maracas": {
        "maracas": "flute",
        "maraca": "flute",
        "maracast": "flutist",
        "maracasts": "flutists",
    },
    "harmonica": {
        "harmonica": "harp",
        "harmonicas": "harps",
        "harpist": "harpist",
        "harpists": "harpists",
        "harmonicaist": "harpist",
        "harmonicaists": "harpists",
    },
    "trombone": {
        "trombone": "xylophone",
        "trombones": "xylophones",
        "trombonist": "xylophonist",
        "trombonists": "xylophonists",
        "tromboneist": "xylophonist",
        "tromboneists": "xylophonists",
    },
    "xylophone": {
        "xylophone": "trombone",
        "xylophones": "trombones",
        "xylophonist": "trombonist",
        "xylophonists": "trombonists",
        "xylophoneist": "trombonist",
        "xylophoneists": "trombonists",
    },
}
