method: textemb
artifact: ""
concept: vocal_style
min-range: -0.294
max-range: 0.424
steps-per-side: 15
method-kwargs: {te_split_step: 0, target_layers: all}
duration: 30.0
steps: 30
guidance-scale: 5.0
seed: 2115
save-dir: outputs/eval/textemb_all_vocal_style
