method: textemb
artifact: ""
concept: electronic_music
min-range: -0.8046
max-range: 0.8697
steps-per-side: 15
method-kwargs: {te_split_step: 0, target_layers: tf6tf7}
duration: 30.0
steps: 30
guidance-scale: 5.0
seed: 2115
save-dir: outputs/eval/textemb_loc_electronic_music
