#! /bin/bash

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 12.0 --num_diffusion_steps 200 --tstart 100 --results_path ../../outputs/medleymd/audioldm2/test --mode ddpm --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song." --layers_to_hook "up_blocks.1.attentions.5.transformer_blocks.0.attn2" "up_blocks.1.attentions.5.transformer_blocks.1.attn2" "up_blocks.1.attentions.9.transformer_blocks.0.attn2" "up_blocks.1.attentions.9.transformer_blocks.1.attn2" "up_blocks.1.attentions.10.transformer_blocks.0.attn2" "up_blocks.1.attentions.10.transformer_blocks.1.attn2"c

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 12.0 --num_diffusion_steps 200 --tstart 100 --results_path ../../outputs/medleymd/audioldm2/test --mode ddpm --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song."

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 5.0 --num_diffusion_steps 200 --tstart 100 --results_path ../../outputs/medleymd/audioldm2/test --mode ddim --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song."

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 5.0 --num_diffusion_steps 200 --tstart 100 --results_path ../../outputs/medleymd/audioldm2/test --mode ddim --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song." --layers_to_hook "up_blocks.1.attentions.5.transformer_blocks.0.attn2" "up_blocks.1.attentions.5.transformer_blocks.1.attn2" "up_blocks.1.attentions.9.transformer_blocks.0.attn2" "up_blocks.1.attentions.9.transformer_blocks.1.attn2" "up_blocks.1.attentions.10.transformer_blocks.0.attn2" "up_blocks.1.attentions.10.transformer_blocks.1.attn2"

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 12.0 --num_diffusion_steps 200 --tstart 60 --results_path ../../outputs/medleymd/audioldm2/test --mode sdedit --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song."

python audioldm_run.py -s 42 --init_aud ../../outputs/medleymd/audioldm2/test/source.wav --cfg_src 3.0 --cfg_tar 12.0 --num_diffusion_steps 200 --tstart 60 --results_path ../../outputs/medleymd/audioldm2/test --mode sdedit --model_id "cvssp/audioldm2-large" --source_prompt "A recording of a rock song." --target_prompt "A recording of a heavy metal song." --layers_to_hook "up_blocks.1.attentions.5.transformer_blocks.0.attn2" "up_blocks.1.attentions.5.transformer_blocks.1.attn2" "up_blocks.1.attentions.9.transformer_blocks.0.attn2" "up_blocks.1.attentions.9.transformer_blocks.1.attn2" "up_blocks.1.attentions.10.transformer_blocks.0.attn2" "up_blocks.1.attentions.10.transformer_blocks.1.attn2"