layers_to_patch:
  - ".unet.up_blocks.1.attentions.11.transformer_blocks.0.attn1"
  - ".unet.up_blocks.1.attentions.11.transformer_blocks.0.attn2"
  - ".unet.up_blocks.1.attentions.11.transformer_blocks.1.attn1"
  - ".unet.up_blocks.1.attentions.11.transformer_blocks.1.attn2" 