def get_prompts_piano(num=50):
    NEUTRAL_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "dissonant music",
        "simple music",
        "complex music",
        "minimalist music",
    ]
    POSITIVE_PROMPTS = [f"{p}, with piano" for p in NEUTRAL_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_mood(num=50):
    BASE_PROMPTS = [
        "song",
        "melody",
        "music",
        "tune",
        "track",
        "composition",
        "instrumental music",
        "piece of music",
        "background music",
        "musical performance",
        "pop song",
        "rock song",
        "jazz piece",
        "classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "ballad",
        "love song",
        "piano music",
        "guitar music",
        "synth music",
        "soundtrack",
        "cinematic music",
        "romantic music",
        "nostalgic music",
        "dreamy music",
        "intense music",
        "soulful music",
        "groovy music",
        "funky music",
        "smooth music",
        "raw music",
        "emotional music",
        "expressive music",
        "duet",
        "solo performance",
        "cover song",
        "original song",
        "remix",
    ]
    POSITIVE_PROMPTS = [f"happy song, {p}" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"sad song, {p}" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_tempo(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "piano music",
        "guitar music",
        "synth music",
        "a soundtrack",
        "cinematic music",
        "happy music",
        "sad music",
        "emotional music",
        "dramatic music",
        "intense music",
        "gentle music",
        "powerful music",
        "soft music",
        "groovy music",
        "funky music",
        "smooth music",
        "a duet",
        "a solo performance",
        "a cover song",
        "an original song",
        "a remix",
    ]
    POSITIVE_PROMPTS = [f"fast song, {p}" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"slow song, {p}" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_vocal_gender(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "a piece of music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "gentle music",
        "powerful music",
        "soft music",
        "an R&B song",
        "a soul song",
        "an indie song",
        "a disco song",
        "a funk song",
        "a gospel song",
        "an opera piece",
        "a lullaby",
        "a duet",
        "a cover song",
        "an original song",
        "a karaoke track",
        "a vocal performance",
    ]
    POSITIVE_PROMPTS = [f"{p}, with female vocal" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"{p}, with male vocal" for p in BASE_PROMPTS]
    LYRICS = """"""  # empty to allow vocals
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_guitar_electronic(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "dissonant music",
        "simple music",
        "complex music",
        "minimalist music",
    ]
    POSITIVE_PROMPTS = [f"{p}, with acoustic guitar" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"{p}, with electric guitar" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_vocal_style(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "a piece of music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "symphonic music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "gentle music",
        "powerful music",
        "soft music",
        "an R&B song",
        "a soul song",
        "an indie song",
        "a disco song",
        "a funk song",
        "a gospel song",
        "an opera piece",
        "a lullaby",
        "a duet",
        "a cover song",
        "an original song",
        "a karaoke track",
        "a vocal performance",
    ]
    POSITIVE_PROMPTS = [f"{p}, with rap vocal" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"{p}, with sing vocal" for p in BASE_PROMPTS]
    LYRICS = """"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_violin(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "dissonant music",
        "simple music",
        "complex music",
        "minimalist music",
    ]
    POSITIVE_PROMPTS = [f"{p}, with violin" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return BASE_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_rock_genre(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "a pop song",
        "a classical piece",
        "hip hop music",
        "country music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "simple music",
        "complex music",
        "minimalist music",
        "an indie song",
        "a cover song",
        "an original song",
        "a soundtrack",
    ]
    POSITIVE_PROMPTS = [f"jazz song, {p}" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"rock song, {p}" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_electronic_music(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "dissonant music",
        "simple music",
        "complex music",
        "minimalist music",
        "an indie song",
        "a cover song",
        "an original song",
        "a duet",
        "a solo performance",
        "a remix",
    ]
    POSITIVE_PROMPTS = [f"classical song, {p}" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"electronic song, {p}" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


CONCEPT_TO_PROMPTS = {
    "piano": get_prompts_piano,
    "mood": get_prompts_mood,
    "tempo": get_prompts_tempo,
    "vocal_gender": get_prompts_vocal_gender,
    "vocal_style": get_prompts_vocal_style,
    "guitar_electronic": get_prompts_guitar_electronic,
    "violin": get_prompts_violin,
    "rock_genre": get_prompts_rock_genre,
    "electronic_music": get_prompts_electronic_music,
}
