"""Unified ``Scorer`` interface for each method's offline (compute / train) phase.

Mirrors :mod:`src.steering.registry` for the inference-time :class:`Controller`:
each steering method registers a ``Scorer`` that turns ``(model, concept,
configs) -> artifact directory``. The unified ``src/steering/run_compute.py`` runner
then drives every method through a single CLI, the way ``run_eval.py`` does for
inference.

Two artifact families:

* **Steering vectors** (CAA, AUSteer, …) — light, generated by a forward pass
  over labelled prompt pairs.
* **Trained networks** (SAE, Concept Slider LoRA) — heavy; the scorer is a thin
  wrapper around the existing training scripts, kept so all phases share a
  single entry point.
"""

from __future__ import annotations

import abc
from pathlib import Path
from typing import Any, Type

from .model import SteerableACEModel


class Scorer(abc.ABC):
    """Compute / train phase of a steering method."""

    @abc.abstractmethod
    def compute(self, model: SteerableACEModel, output_dir: str | Path, **kwargs: Any) -> Path:
        """Run the compute / train job and write artifacts under ``output_dir``.

        Returns the path to the artifact directory that is then consumable by
        the corresponding ``Controller.from_pretrained``.
        """


# ---------------------------------------------------------------------------
# Scorer registry — parallel to ``register_method``.
# ---------------------------------------------------------------------------

_REGISTRY: dict[str, Type[Scorer]] = {}


def register_scorer(name: str):
    """Class decorator to register a :class:`Scorer` under ``name``.

    Names typically match the controller name (``caa``, ``sae``, …) but can
    use a ``<method>-<phase>`` form for methods with multiple phases (e.g.
    ``sae-activations``, ``sae-train``).
    """

    def _decorator(cls: Type[Scorer]) -> Type[Scorer]:
        if not issubclass(cls, Scorer):
            raise TypeError(f"{cls.__name__} must subclass Scorer to register.")
        if name in _REGISTRY and _REGISTRY[name] is not cls:
            raise ValueError(
                f"Scorer {name!r} is already registered to {_REGISTRY[name].__name__}."
            )
        _REGISTRY[name] = cls
        return cls

    return _decorator


def get_scorer(name: str) -> Type[Scorer]:
    if name not in _REGISTRY:
        raise KeyError(
            f"Unknown scorer {name!r}. Registered: {sorted(_REGISTRY)}."
        )
    return _REGISTRY[name]


def list_scorers() -> list[str]:
    return sorted(_REGISTRY)
