layers_to_patch:
  - ".unet.up_blocks.0.attentions.0.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.0.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.0.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.0.transformer_blocks.1.attn2"
  - ".unet.up_blocks.0.attentions.1.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.1.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.2.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.2.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.3.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.3.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.3.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.3.transformer_blocks.1.attn2"
  - ".unet.up_blocks.0.attentions.4.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.4.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.4.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.4.transformer_blocks.1.attn2"
  - ".unet.up_blocks.0.attentions.5.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.5.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.6.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.6.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.7.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.7.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.7.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.7.transformer_blocks.1.attn2"
  - ".unet.up_blocks.0.attentions.8.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.8.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.8.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.8.transformer_blocks.1.attn2"
  - ".unet.up_blocks.0.attentions.9.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.9.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.10.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.10.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.11.transformer_blocks.0.attn1"
  - ".unet.up_blocks.0.attentions.11.transformer_blocks.0.attn2"
  - ".unet.up_blocks.0.attentions.11.transformer_blocks.1.attn1"
  - ".unet.up_blocks.0.attentions.11.transformer_blocks.1.attn2" 